# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
xcodeproj 'AnyThinkSDKDemo.xcodeproj'

target 'AnyThinkSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AnyThinkiOS','5.5.8'
  pod 'AnyThinkiOS/AnyThinkFacebookAdapter','5.5.8'
  pod 'FBAudienceNetwork' , '5.9.0'
  pod 'AnyThinkiOS/AnyThinkAdmobAdapter','5.5.8'
  pod 'Google-Mobile-Ads-SDK','7.60.0'
  pod 'PersonalizedAdConsent'
  pod 'AnyThinkiOS/AnyThinkTouTiaoAdapter','5.5.8'
#  pod 'Bytedance-UnionAD' , '3.0.0.1'
  pod 'AnyThinkiOS/AnyThinkApplovinAdapter','5.5.8'
  pod 'AppLovinSDK', '6.12.6'
  pod 'AnyThinkiOS/AnyThinkMintegralAdapter','5.5.8'
  pod 'MintegralAdSDK' ,'6.2.0'
  pod 'MintegralAdSDK/RewardVideoAd','6.2.0'
  pod 'MintegralAdSDK/BidRewardVideoAd','6.2.0'
  pod 'MintegralAdSDK/BidInterstitialVideoAd','6.2.0'
  pod 'MintegralAdSDK/InterstitialVideoAd','6.2.0'
  pod 'MintegralAdSDK/InterstitialAd','6.2.0'
  pod 'MintegralAdSDK/BannerAd' ,'6.2.0'
  pod 'MintegralAdSDK/BidBannerAd','6.2.0'
  pod 'AnyThinkiOS/AnyThinkGDTAdapter','5.5.8'
  pod 'GDTMobSDK', '4.11.8'
  pod 'AnyThinkiOS/AnyThinkUnityAdsAdapter','5.5.8'
  pod 'UnityAds' , '3.4.2'
  pod 'AnyThinkiOS/AnyThinkChartboostAdapter','5.5.8'
  pod 'ChartboostSDK','8.1.0'
  pod 'AnyThinkiOS/AnyThinkTapjoyAdapter','5.5.8'
  pod 'TapjoySDK','12.4.2'
  pod 'AnyThinkiOS/AnyThinkNendAdapter','5.5.8'
  pod 'NendSDK_iOS','5.3.1'
  pod 'AnyThinkiOS/AnyThinkIronSourceAdapter','5.5.8'
  pod 'IronSourceSDK','6.16.1'
  pod 'AnyThinkiOS/AnyThinkInmobiAdapter','5.5.8'
  pod 'InMobiSDK' ,'9.0.7'
  pod 'AnyThinkiOS/AnyThinkAppnextAdapter','5.5.8'
  #第三方不支持pod,请另行下载
  pod 'AnyThinkiOS/AnyThinkAdcolonyAdapter','5.5.8'
  pod 'AdColony','4.1.4.0'
  pod 'AnyThinkiOS/AnyThinkVungleAdapter','5.5.8'
#  pod 'VungleSDK-iOS', '6.5.4'
  pod 'AnyThinkiOS/AnyThinkMaioAdapter','5.5.8'
  pod 'MaioSDK','1.5.0'
  pod 'AnyThinkiOS/AnyThinkKSAdapter','5.5.8'
  pod 'KSAdSDK', '2.6.5.1'
  pod 'SDWebImage'
  pod 'AnyThinkiOS/AnyThinkBaiduAdapter','5.5.8'
  #第三方不支持pod,请另行下载
  pod 'AnyThinkiOS/AnyThinkOguryAdapter','5.5.8'
  #第三方不支持pod,请另行下载
  pod 'AnyThinkiOS/AnyThinkOnewayAdapter','5.5.8'
  #第三方不支持pod,请另行下载
  pod 'AnyThinkiOS/AnyThinkSigmobAdapter','5.5.8'
  pod 'SigmobAd-iOS', '2.18.0'
  pod 'AnyThinkiOS/AnyThinkStartAppAdapter','5.5.8'
  pod 'StartAppSDK', '4.5.0'
  pod 'AnyThinkiOS/AnyThinkFyberAdapter','5.5.8'
  pod 'Fyber_Marketplace_SDK', '7.5.4'


end
