# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
project 'AnyThinkSDKDemo.xcodeproj'

def share_pods
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJRefresh'


end

target 'AnyThinkSDKDemo' do
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  share_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AnyThinkiOS','6.1.74'
  pod 'AnyThinkiOS/AnyThinkAdmobAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkPangleAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkTTAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkFacebookAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkGDTAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkMintegralAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkApplovinAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkTapjoyAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkChartboostAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkUnityAdsAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkVungleAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkInmobiAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkIronSourceAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkMaioAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkNendAdapter','6.1.74'
#  pod 'AnyThinkiOS/AnyThinkSigmobAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkStartAppAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkKidozAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkFyberAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkMyTargetAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkKuaiShouAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkBaiduAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkOguryAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkAdColonyAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkYandexAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkBigoAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkPubNativeAdapter','6.1.74'
  pod 'AnyThinkiOS/AnyThinkKlevinAdapter','6.1.74'


#https://topon-sdk-release.oss-cn-hangzhou.aliyuncs.com/SDK_Release/v6.1.74/iOS/AnyThink_mediation/AnyThinkiOS.zip
  
## 本地pod
#  pod 'LocalThirdPartySDK/core', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/admob', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/applovin', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/baidu', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/chartboost', :path=> 'LSDK/'
##  pod 'LocalThirdPartySDK/facebook', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/fyber', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/gdt', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/inmobi', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/ironsource', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/kidoz', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/kuaishou', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/maio', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/applovin', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/AppLovinMediationAdColonyAdapter', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/AppLovinMediationChartboostAdapter', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/AppLovinMediationTapjoyAdapter', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/mintegral', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/mobrain', :path=> 'LSDK/'
##  pod 'LocalThirdPartySDK/mopub', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/MyTarget', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/nend', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/ogury', :path=> 'LSDK/'
##  pod 'LocalThirdPartySDK/pangle_noChina', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/pangle_china_common', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/pangle_China', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/klevin', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/sigmob', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/startapp', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/tapjoy', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/unityads', :path=> 'LSDK/'
#  pod 'LocalThirdPartySDK/vungle', :path=> 'LSDK/'

end 
