# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
project 'AnyThinkSDKDemo.xcodeproj'

target 'AnyThinkSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'AnyThinkiOS','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkAdmobAdapter','5.8.12'
##  pod 'AnyThinkiOS/AnyThinkPangleAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkTTAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkFacebookAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkGDTAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkMintegralAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkApplovinAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkTapjoyAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkChartboostAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkUnityAdsAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkVungleAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkInmobiAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkIronSourceAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkMaioAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkNendAdapter','5.8.12'
##  pod 'AnyThinkiOS/AnyThinkSigmobAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkStartAppAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkKidozAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkFyberAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkMyTargetAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkKSAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkBaiduAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkOguryAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkMopubAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkAdColonyAdapter','5.8.12'
#  pod 'AnyThinkiOS/AnyThinkKlevinAdapter','5.8.12'


# 本地pod
  pod 'LocalThirdPartySDK/core', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/admob', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/applovin', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/baidu', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/chartboost', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/facebook', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/fyber', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/gdt', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/inmobi', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/ironsource', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/kidoz', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/kuaishou', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/maio', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/applovin', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/AppLovinMediationAdColonyAdapter', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/AppLovinMediationChartboostAdapter', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/AppLovinMediationTapjoyAdapter', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/mintegral', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/mobrain', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/mopub', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/MyTarget', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/nend', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/ogury', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/pangle_noChina', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/pangle_china_common', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/pangle_China', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/klevin', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/sigmob', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/startapp', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/tapjoy', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/unityads', :path=> 'SDK/'
  pod 'LocalThirdPartySDK/vungle', :path=> 'SDK/'









end
